apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: spring-petclinic
  annotations:
    github.com/project-slug: ftovaro/spring-petclinic
spec:
  type: other
  lifecycle: unknown
  owner: default-team
